/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UslugiRouteImport } from './routes/uslugi'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ONasRouteImport } from './routes/o-nas'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UslugiIndexRouteImport } from './routes/uslugi.index'
import { Route as UslugiZarzadzanieNieruchomosciamiRouteImport } from './routes/uslugi.zarzadzanie-nieruchomosciami'
import { Route as UslugiTechnikaGrzewczaRouteImport } from './routes/uslugi.technika-grzewcza'
import { Route as UslugiKonserwacjaNieruchomosciRouteImport } from './routes/uslugi.konserwacja-nieruchomosci'

const UslugiRoute = UslugiRouteImport.update({
  id: '/uslugi',
  path: '/uslugi',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ONasRoute = ONasRouteImport.update({
  id: '/o-nas',
  path: '/o-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiIndexRoute = UslugiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UslugiRoute,
} as any)
const UslugiZarzadzanieNieruchomosciamiRoute =
  UslugiZarzadzanieNieruchomosciamiRouteImport.update({
    id: '/zarzadzanie-nieruchomosciami',
    path: '/zarzadzanie-nieruchomosciami',
    getParentRoute: () => UslugiRoute,
  } as any)
const UslugiTechnikaGrzewczaRoute = UslugiTechnikaGrzewczaRouteImport.update({
  id: '/technika-grzewcza',
  path: '/technika-grzewcza',
  getParentRoute: () => UslugiRoute,
} as any)
const UslugiKonserwacjaNieruchomosciRoute =
  UslugiKonserwacjaNieruchomosciRouteImport.update({
    id: '/konserwacja-nieruchomosci',
    path: '/konserwacja-nieruchomosci',
    getParentRoute: () => UslugiRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uslugi': typeof UslugiRouteWithChildren
  '/uslugi/konserwacja-nieruchomosci': typeof UslugiKonserwacjaNieruchomosciRoute
  '/uslugi/technika-grzewcza': typeof UslugiTechnikaGrzewczaRoute
  '/uslugi/zarzadzanie-nieruchomosciami': typeof UslugiZarzadzanieNieruchomosciamiRoute
  '/uslugi/': typeof UslugiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uslugi/konserwacja-nieruchomosci': typeof UslugiKonserwacjaNieruchomosciRoute
  '/uslugi/technika-grzewcza': typeof UslugiTechnikaGrzewczaRoute
  '/uslugi/zarzadzanie-nieruchomosciami': typeof UslugiZarzadzanieNieruchomosciamiRoute
  '/uslugi': typeof UslugiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uslugi': typeof UslugiRouteWithChildren
  '/uslugi/konserwacja-nieruchomosci': typeof UslugiKonserwacjaNieruchomosciRoute
  '/uslugi/technika-grzewcza': typeof UslugiTechnikaGrzewczaRoute
  '/uslugi/zarzadzanie-nieruchomosciami': typeof UslugiZarzadzanieNieruchomosciamiRoute
  '/uslugi/': typeof UslugiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galeria'
    | '/kontakt'
    | '/o-nas'
    | '/sitemap.xml'
    | '/uslugi'
    | '/uslugi/konserwacja-nieruchomosci'
    | '/uslugi/technika-grzewcza'
    | '/uslugi/zarzadzanie-nieruchomosciami'
    | '/uslugi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeria'
    | '/kontakt'
    | '/o-nas'
    | '/sitemap.xml'
    | '/uslugi/konserwacja-nieruchomosci'
    | '/uslugi/technika-grzewcza'
    | '/uslugi/zarzadzanie-nieruchomosciami'
    | '/uslugi'
  id:
    | '__root__'
    | '/'
    | '/galeria'
    | '/kontakt'
    | '/o-nas'
    | '/sitemap.xml'
    | '/uslugi'
    | '/uslugi/konserwacja-nieruchomosci'
    | '/uslugi/technika-grzewcza'
    | '/uslugi/zarzadzanie-nieruchomosciami'
    | '/uslugi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriaRoute: typeof GaleriaRoute
  KontaktRoute: typeof KontaktRoute
  ONasRoute: typeof ONasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UslugiRoute: typeof UslugiRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uslugi': {
      id: '/uslugi'
      path: '/uslugi'
      fullPath: '/uslugi'
      preLoaderRoute: typeof UslugiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nas': {
      id: '/o-nas'
      path: '/o-nas'
      fullPath: '/o-nas'
      preLoaderRoute: typeof ONasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/': {
      id: '/uslugi/'
      path: '/'
      fullPath: '/uslugi/'
      preLoaderRoute: typeof UslugiIndexRouteImport
      parentRoute: typeof UslugiRoute
    }
    '/uslugi/zarzadzanie-nieruchomosciami': {
      id: '/uslugi/zarzadzanie-nieruchomosciami'
      path: '/zarzadzanie-nieruchomosciami'
      fullPath: '/uslugi/zarzadzanie-nieruchomosciami'
      preLoaderRoute: typeof UslugiZarzadzanieNieruchomosciamiRouteImport
      parentRoute: typeof UslugiRoute
    }
    '/uslugi/technika-grzewcza': {
      id: '/uslugi/technika-grzewcza'
      path: '/technika-grzewcza'
      fullPath: '/uslugi/technika-grzewcza'
      preLoaderRoute: typeof UslugiTechnikaGrzewczaRouteImport
      parentRoute: typeof UslugiRoute
    }
    '/uslugi/konserwacja-nieruchomosci': {
      id: '/uslugi/konserwacja-nieruchomosci'
      path: '/konserwacja-nieruchomosci'
      fullPath: '/uslugi/konserwacja-nieruchomosci'
      preLoaderRoute: typeof UslugiKonserwacjaNieruchomosciRouteImport
      parentRoute: typeof UslugiRoute
    }
  }
}

interface UslugiRouteChildren {
  UslugiKonserwacjaNieruchomosciRoute: typeof UslugiKonserwacjaNieruchomosciRoute
  UslugiTechnikaGrzewczaRoute: typeof UslugiTechnikaGrzewczaRoute
  UslugiZarzadzanieNieruchomosciamiRoute: typeof UslugiZarzadzanieNieruchomosciamiRoute
  UslugiIndexRoute: typeof UslugiIndexRoute
}

const UslugiRouteChildren: UslugiRouteChildren = {
  UslugiKonserwacjaNieruchomosciRoute: UslugiKonserwacjaNieruchomosciRoute,
  UslugiTechnikaGrzewczaRoute: UslugiTechnikaGrzewczaRoute,
  UslugiZarzadzanieNieruchomosciamiRoute:
    UslugiZarzadzanieNieruchomosciamiRoute,
  UslugiIndexRoute: UslugiIndexRoute,
}

const UslugiRouteWithChildren =
  UslugiRoute._addFileChildren(UslugiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriaRoute: GaleriaRoute,
  KontaktRoute: KontaktRoute,
  ONasRoute: ONasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UslugiRoute: UslugiRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
